kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/one-byte-data/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag

services:
  - name: cockroachdb
    image: cockroachdb/cockroach:latest
    commands:
      - cockroach start-single-node --insecure --advertise-addr=cockroachdb
    
steps:
  - name: unit-test
    image: golang:latest
    commands:
      - go test -coverprofile=unit-coverage.txt ./...

  - name: integration-test
    image: golang:latest
    commands:
      - go test -p 1 -coverprofile=integration-coverage.txt ./... -run TestIntegration\*

  - name: benchmark
    image: golang:latest
    commands:
      - cd internal/controllers && go test -benchmem -run="^#" -bench . && cd ../..
      - cd internal/services && go test -benchmem -run="^#" -bench . && cd ../..

  - name: build
    image: golang:latest
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - swag init -d cmd/server
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/docker/go-api-sample cmd/server/main.go

  - name: docker-dev
    image: plugins/docker
    when:
      branch:
        - main
      event:
        - push
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      registry: ghcr.io
      repo: ghcr.io/one-byte-data/${DRONE_REPO_NAME}
      tags:
        - dev

  - name: docker-latest
    image: plugins/docker
    when:
      branch:
        - main
      event:
        - tag
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      registry: ghcr.io
      repo: ghcr.io/one-byte-data/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}
