kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/JustSomeHack/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag

services:
  - name: cockroachdb
    image: cockroachdb/cockroach:latest
    commands:
      - cockroach start-single-node --insecure --advertise-addr=cockroachdb
    
steps:
  - name: test
    image: golang:latest
    commands:
      - go test -p 1 -coverprofile=coverage.txt ./...

  - name: benchmark
    image: golang:latest
    commands:
      - cd internal/controllers && go test -benchmem -run="^#" -bench . && cd ../..
      - cd internal/services && go test -benchmem -run="^#" -bench . && cd ../..

  - name: build
    image: golang:latest
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - swag init -d cmd/server
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/docker/go-api-sample cmd/server/main.go

  # - name: docker
  #   image: plugins/docker
